[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "opt-level=3",
    "-C", "codegen-units=1",
    "-C", "embed-bitcode=yes",
    "-C", "lto=thin",
    "-C", "linker=clang",
    "-C", "link-arg=-fuse-ld=mold",
    "-C", "linker-plugin-lto=/usr/x86_64-pc-linux-gnu/binutils-bin/lib/bfd-plugins/LLVMgold.so"
]
